### ISSUE TITLE
May I have the paper please :)

### ISSUE THREAD

**Issue by bopeng87** [ZSVOS/HCPN#1]
Congratulations on winning the Davis challenges~  
Really looking forward to reading your paper!  I wonder if it's convenient to share it with me? My email is pengbo87@gmail.com   Thx a lot~ 
Hierarchical Co-attention Propagation Network for Zero-Shot Video Object Segmentation

**Comment by ZSVOS** [comment]
Thank you for your affirmation. Since the paper is still in anonymous submission, it may not be available to you now. I will post the paper to arXiv as soon as the results are returned. Please stay tuned.

**Comment by bopeng87** [comment]
thx a lot~
